#!/bin/bash
################################################################################
# Copyright 2008 by Tommi Rantala <tommi.rantala@cs.helsinki.fi>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
################################################################################
#
# Postprocesses the outputs from the tools we have used to gather data to HTML.
#
################################################################################
for E in tool-output/memusage_* ; do
	case $E in
		*.html | *~) ;;
		*)
		echo "<html><body><pre>" > $E.html
		# Rip ASCII color codes for now, maybe convert to equivalent CSS colors?
		sed 's/\x1b\[[0-9][0-9]*;*[0-9]*m//g' $E >> $E.html
		# Append baseline results
		echo "</pre><hr/>Baseline:<pre>" >> $E.html
		sed 's/\x1b\[[0-9][0-9]*;*[0-9]*m//g' `echo $E | sed 's/_[0-9]*\$//'`_0 >> $E.html
		echo "</pre></body></html>" >> $E.html
		;;
	esac
done
