#!/bin/bash
################################################################################
# Copyright 2008 by Tommi Rantala <tommi.rantala@cs.helsinki.fi>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
################################################################################
function die() {
	echo "ERROR: $1"
	exit 1
}
################################################################################
if [[ -z $EVENTS ]] ; then
	EVENTS="CPU_CLK_UNHALTED:100000
		LOAD_BLOCK:10000:0x02
		LOAD_BLOCK:10000:0x04
		LOAD_BLOCK:10000:0x08
		LOAD_BLOCK:10000:0x10
		LOAD_BLOCK:10000:0x20
		STORE_BLOCK:10000:0x02
		INST_RETIRED:100000
		DTLB_MISSES:10000
		MEM_LOAD_RETIRED:10000:0x02
		MEM_LOAD_RETIRED:10000:0x08
		L2_LINES_IN:10000
		L1D_CACHE_LD:10000
		SIMD_INST_RETIRED:100000"
fi
################################################################################
if [[ -z $BIN  ]] ; then BIN=./sortstring ; fi
if [[ ! -x $BIN ]] ; then die "Sorry, binary not executable" ; fi
if [[ -z $ALGS ]] ; then ALGS=`$BIN --alg-nums` ; fi
if [[ -z $INFILES ]] ; then INFILES="input/url3 input/nodup3 input/genome3" ; fi
if [[ -z $OUTDIR ]] ; then OUTDIR="data" ; fi
mkdir -p $OUTDIR
if [[ -z $TOOLOUTDIR ]] ; then TOOLOUTDIR="tool-output"; fi
for I in $INFILES ; do
        if [[ ! -r "$I" ]] ; then die "Sorry, ''$I'' not readable" ; fi
done
# Oprofile requires absolute path.
OPSESSIONDIR=$PWD/$TOOLOUTDIR/oprofile-session-dir
################################################################################
echo "ALGS=$ALGS"
echo "EVENTS=$EVENTS"
echo "INFILES=$INFILES"
echo "Processing XML ..."
for FILE in $INFILES ; do
	echo "   Input file $FILE ..."
	BFILE=`basename "$FILE"`
	for ALG in $ALGS ; do
		XMLOUT="$OUTDIR/oprofile_${BFILE}_${ALG}.xml"
		echo "<simple>" > $XMLOUT || die "Could not create $XMLOUT"
		for EVENT in $EVENTS ; do
			NICE_EVENT="`echo $EVENT | sed 's/:/_/g'`"
			SESSIONNAME="${BFILE}_${ALG}_${NICE_EVENT}"
			opreport --session-dir=$OPSESSIONDIR --xml \
				session:$SESSIONNAME $BIN >.report 2>/dev/null
			if [[ $? -ne 0 ]] ; then
				echo "WARNING: session $SESSIONNAME failed"
			else
				xsltproc oprofile-simplify.xsl .report >> $XMLOUT
			fi
			rm -f .report
		done
		echo "</simple>" >> $XMLOUT
	done
done
echo "Processing HTML ..."
for FILE in $INFILES ; do
	echo "   Input file $FILE ..."
	BFILE=`basename "$FILE"`
	for ALG in $ALGS ; do
		for EVENT in $EVENTS ; do
			# convert : -> _
			NICE_EVENT="`echo $EVENT | tr : _`"
			SESSIONNAME="${BFILE}_${ALG}_${NICE_EVENT}"
			# strip event count for HTML file name:
			#   STORE_BLOCK:10000:0x02  -> STORE_BLOCK_0x02
			#   DTLB_MISSES:10000       -> DTLB_MISSES
			HTML_EVENT="`echo $EVENT | awk -F: '{if (\$3) print \$1 "_" \$3; else print \$1;}'`"
			HTMLOUT="$OUTDIR/opannotate_${BFILE}_${ALG}_${HTML_EVENT}.html"
			opannotate --session-dir=$OPSESSIONDIR \
				session:$SESSIONNAME --demangle smart --source \
				--threshold 2 >> .report
			ST=$?
			if [[ $ST -eq 0 ]] ; then
				if [[ -x "./cpp2html" ]] ; then
					./cpp2html .report > $HTMLOUT
				else
					echo "<html><body><pre>" > $HTMLOUT
					cat .report >> $HTMLOUT
					echo "</pre></body></html>" >> $HTMLOUT
				fi
			fi
			rm -f .report
		done
	done
done
